
apiVersion: v1
kind: Service
metadata:
  name: mysql-wordpress
  namespace: wordpress
  labels:
    app: mysql
    tier: backend
    env: development
spec:
  selector:
    app: mysql
    tier: backend
    env: development
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None

