
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

